INSERT INTO categories (name)
VALUES ('Fruits'),
       ('Vegetables'),
       ('Dairy'),
       ('Bakery'),
       ('Beverages'),
       ('Snacks'),
       ('Rice & Grains'),
       ('Meat'),
       ('Seafood'),
       ('Household');

INSERT INTO products (name, price, description, category_id)
VALUES ('Cavendish Bananas (1kg)',
        650.00,
        'Fresh ripe Cavendish bananas sourced from local farms. Rich in potassium and perfect for smoothies or snacks.',
        1),
       ('Fresh Carrots (500g)',
        420.00,
        'Crunchy fresh carrots ideal for salads, soups, and cooking. High in vitamin A.',
        2),
       ('Anchor Full Cream Milk 1L',
        780.00,
        'Fresh full cream milk with essential vitamins and calcium for the whole family.',
        3),
       ('Whole Wheat Bread',
        290.00,
        'Soft whole wheat bread baked daily. Perfect for breakfast and sandwiches.',
        4),
       ('Coca-Cola 1.5L',
        520.00,
        'Refreshing carbonated soft drink served chilled for the best taste.',
        5),
       ('Lays Classic Potato Chips 180g',
        680.00,
        'Crispy salted potato chips made from premium quality potatoes.',
        6),
       ('Nadu Rice 5kg',
        1450.00,
        'Premium Sri Lankan Nadu rice suitable for everyday meals.',
        7),
       ('Chicken Breast Boneless (1kg)',
        1980.00,
        'Fresh boneless chicken breast trimmed and ready for cooking. High in protein.',
        8),
       ('Fresh Tuna Fillet (500g)',
        1650.00,
        'Fresh tuna fillet ideal for grilling, frying, or curries.',
        9),
       ('Sunlight Lemon Dishwashing Liquid 500ml',
        590.00,
        'Powerful grease-cutting dishwashing liquid with a refreshing lemon fragrance.',
        10);